### ISSUE TITLE
Develop plot.ly viewers for Jupyter version of glue

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-plotly#3]
It would be interesting to explore whether plot.ly can be used to power viewers inside the Jupyter version of glue (being developed at https://github.com/glue-viz/glue-jupyter). If anyone is interested in tackling this, you should start off by reading the following guide:

* [Writing a custom viewer for glue](http://docs.glueviz.org/en/stable/customizing_guide/viewer.html)

and seeing how e.g. the bqplot viewers are implemented in glue-jupyter. Note that the state classes in glue-core and the widgets to interact with the state classes in glue-jupyter can probably be re-used. I can provide more details about this issue if anyone wants to work on it!

**Comment by Carifio24** [comment]
With #40 and some of the following PRs we have working implementations of Plotly-powered scatter and histogram viewers for glue-jupyter, so this can be closed. It would be nice to add other viewer types (image, profile, etc.)
